"""empty message

Revision ID: 1e2ef721ef71
Revises: 
Create Date: 2022-12-01 19:45:20.538867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2ef721ef71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university__career',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contestant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=250), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('types_id', sa.Integer(), nullable=True),
    sa.Column('genders_id', sa.Integer(), nullable=True),
    sa.Column('university_careers_id', sa.Integer(), nullable=True),
    sa.Column('inscription_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participation_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['genders_id'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['types_id'], ['type.id'], ),
    sa.ForeignKeyConstraint(['university_careers_id'], ['university__career.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contestant')
    op.drop_table('university__career')
    op.drop_table('type')
    op.drop_table('gender')
    # ### end Alembic commands ###
